### ISSUE TITLE
Support returning a list of suggested challenges

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#11]

**Comment by taha-k** [comment]
What are the criterion's to look for before suggesting? Maybe we can find a users friends via facebook and give suggestions based on that information

**Comment by FruitieX** [comment]
We can also eventually find what challenges other people in your communities are doing. We might want to do this for suggested actions as well.

**Comment by FruitieX** [comment]
Maybe ranked by combined score of top actions from all your communities

**Comment by FruitieX** [comment]
Challenges to be replaced by achievements.
