### ISSUE TITLE
Ratings for challenges and communities as well

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#13]
Just like with actions, it should be possible to rate challenges and communities + add a comment field for feedback.

**Comment by FruitieX** [comment]
Challenges already implemented

**Comment by yesgee** [comment]
Unit tested. Ready to merge with master -> Pull request https://github.com/CIVIS-project/YouPower/pull/48

**Comment by yesgee** [comment]
Merged with master. Closed.
