### ISSUE TITLE
Feedback for actions, communities should have multiple comment fields

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#14]
It should be possible for the frontend to show and save a form with multiple questions instead of just the one `comment` string we have currently.

Could be accomplished just by replacing the current `comment` string in a review with a JSON object where the key is the question itself and value is the answer to the question. REST API would also receive this JSON object instead of a string for the rating API calls.

**Comment by FruitieX** [comment]
Is this still needed/wanted?

**Comment by sanja7s** [comment]
@FruitieX  does this mean something like the new feature of Facebook, where a comment is not anymore to the whole thread, but to a specific comment inside it?

If it is this, it is very good if we have that.

**Comment by FruitieX** [comment]
This is mostly for sending feedback that won't be publicly visible, the question was if it's enough that we have one comment field or if we should have separate fields such as "what was good about the action?" and "what could be improved?" etc.

**Comment by FruitieX** [comment]
@yilinh We now have action comments where the user can enter a comment on an action either while they are doing an action or after they have done an action, (currently we don't separate between these scenarios, should we?)

The old feedback API call is now just generic feedback for the whole app. It can optionally contain multiple fields, it's up to the frontend how many fields are accepted.

Does it sound ok the way it is now, can we close the issue?

**Comment by yilinh** [comment]
yes, please. thanks.
