### ISSUE TITLE
Challenges may have a goal

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#16]
Challenges should support setting an optional goal, for example a specific number of leaves earned through actions taken in the challenge. (How do we store these criteria, and how especially do we support different criteria?)

**Comment by yesgee** [comment]
Off topic, so challenges do have actions?.

**Comment by FruitieX** [comment]
As far as I understand, yes. But let's discuss this matter in the next meeting.

**Comment by FruitieX** [comment]
Maybe merge actions and challenges? E.g. "complete 5 other actions to finish this action"

Or this: #47

**Comment by FruitieX** [comment]
Yeah let's see the outcome of #47 first.

**Comment by FruitieX** [comment]
Challenges to be replaced by achievements.
