### ISSUE TITLE
Should top community actions include done actions or only in progress actions?

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#19]
Discuss. Easy one-liner code change once we have decided.

**Comment by FruitieX** [comment]
In a meeting, we agreed to prioritize in progress actions. When sorting, give a higher priority to in progress actions than done actions so they appear higher up

**Comment by sanja7s** [comment]
And front end can show them in different color

**Comment by FruitieX** [comment]
= When sorting, give a higher priority to in progress actions than done actions so they appear higher up

**Comment by yesgee** [comment]
Isn't what we have already doing this?

**Comment by FruitieX** [comment]
I think they now have equal priority, however that might be fine also.

**Comment by yesgee** [comment]
I'll try to add a priority field to see if that might work.

**Comment by FruitieX** [comment]
Hmm priority should be based on the action's state though, not a separate field. For example an in progress action always has priority 2 when sorting, while a done action only has priority 1.

**Comment by yesgee** [comment]
This would be easier to do from the front end and we give them 'Done' actions and 'In progress' actions  as objects.
