### ISSUE TITLE
Creating a household adds you as the only member of that household

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#21]

**Comment by FruitieX** [comment]
Currently creating a household requires you to specify a list of members, so this code should be replaced so it only adds you as a member.

**Comment by sanja7s** [comment]
we need to ensure one-to-one mapping between the household id and apartmentID

**Comment by FruitieX** [comment]
Creating household = joining household, always ask user for `apartmentId` when "creating" a household, then check if it already exists in our system. If it exists, just join the user with that household, otherwise ask the reply backend if the `apartmentId` is valid, then create a new household for the user. If it's invalid according to reply, show error to user.

Here we treat the `apartmentId` like a secret.

**Comment by sanja7s** [comment]
When a new member wants to join already created household, we also ask the FamilyID from her. That adds security when connecting first time to the household.

**Comment by yesgee** [comment]
For those with smart meter: 
On creation of household, we check if a household with the apartment ID (from usage point) is already existing. If no, new household is created and the user is added as the member. 
Note: Should also check if the apartment id provided is valid

If the household exists, the user should be asked for another id(family id?) to authenticate (Possibly also entered by the user who is creating the household in the first place). On authentication, he is added as a member of the household. (To do)

Tagging @FruitieX

**Comment by FruitieX** [comment]
For now, let's assume the apartment ID is valid. (we probably don't even have a way of validating it yet...)

Not sure, what is the FamilyID? I'd say for the time being, let's just go with the apartment ID as our "secret". I'll add the `needs discussion` label to this issue so we can talk about this tomorrow in our meeting.

**Comment by sanja7s** [comment]
Yes, we need to discuss this. Perhaps you were not involved in discussion with Reply, but only @CodeTaha -- basically FamilyID needs to be our secret. We cannot assume it to be apartmentID, because that is a sequential number given by Reply.
So yep let's talk tomorrow!
