### ISSUE TITLE
Implement private communities

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#22]
Public communities (default) are visible in community listings, private communities are not. Anyone can join public communities, while private communities require an invite (see #23).

At least for now, every member of the community will be able to invite others.

**Comment by FruitieX** [comment]
Every user can invite

**Comment by yesgee** [comment]
In addition to listing and joining communities, not all members of a community should  be allowed to 'delete' a community or 'remove' members.  So I am thinking we need an authorization logic for communities as a whole. 
May be we can have roles like 'owner', 'moderator' and 'members' in the community model and somehow control the actions each can perform on the community?

**Comment by FruitieX** [comment]
For now, maybe it's enough to only allow the owner (whoever created the community) to delete & remove members, Assign e.g. an `ownerId` to the community matching the `userId` of the creator and compare to this whenever trying to delete/remove. Later we can think of how to do the authorization stuff so that more people can "admin" a community

**Comment by yesgee** [comment]
Implemented : Only community owners can remove members. 

To do: Private communities shouldn't be visible to non members

**Comment by yesgee** [comment]
Implemented: Listing only 'Open' communities
Bug : This is yet to be tested since there is some cyclic dependency on the users/communities data. Needs discussion.

**Comment by yesgee** [comment]
Need to discuss where to have the reference, in community or user? or have a separate reference document with community and user reference ids?

**Comment by yesgee** [comment]
Implemented:
- Querying complete communities list for user will only list 'Open' Communities.
- Only community owners can remove members.

Note: Removed the community reference from the user model to avoid cyclic dependency.
