### ISSUE TITLE
Possibility to send community invites to users of the app?

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#23]
Do we limit this to your friends only in order to prevent spam?

**Comment by FruitieX** [comment]
This could be implemented so that the community model will have a list of userId:s that have been invited, and those users can then join the community at will (and are then removed from the invited users list).

TODO: how do we notify the user? Do we include a list of communities the user has been invited to on the home page of the app?

**Comment by FruitieX** [comment]
- Not only limited to friends.
- Tab (in frontend) for invites?

**Comment by yesgee** [comment]
Invite non members- invite to app to sign up. Need to think about how to do this, via email?
Invite members- pop up on user home page for community invite.

**Comment by FruitieX** [comment]
This feature should be limited to people who are already using the app, so we don't have to worry about e-mails here :)

**Comment by yesgee** [comment]
Oops yeah. 
During the meeting, we were discussing how to invite non members to the app and in turn let them sign up.

**Comment by FruitieX** [comment]
Should this be done with push notifications? In that case we have to wait for that functionality

**Comment by yesgee** [comment]
This is handled here. https://github.com/CIVIS-project/YouPower/issues/76.
