### ISSUE TITLE
It should be possible to comment on actions, challenges, communities

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#25]
It should be possible to leave comments on actions, challenges and communities, and engage in discussions around these.

**Comment by FruitieX** [comment]
Idea for implementing: create new `ActionComments`, `ChallengeComments` and `CommunityComments` models, and create comments into these with actionId, challengeId or communityId set to the respective id of what the user is commenting on. Remember a timestamp for each comment so they can be sorted by date.

**Comment by yilinh** [comment]
can comment include pictures too? 
Additionally, Hanna and I were thinking about putting pictures to action descriptions.

**Comment by FruitieX** [comment]
I'll open a separate issue for pictures in comments

**Comment by yilinh** [comment]
Hi Rasmus,

Sanja and Hanna were also talking about having pictures for the tips. Maybe you can also take that into consideration? 

Kind regards,
Yilin

**Comment by FruitieX** [comment]
Yeah, probably a similar system there

**Comment by FruitieX** [comment]
Commenting is now possible for Actions. Will do challenges and communities as well.
