### ISSUE TITLE
Allow setting type of house when creating/editing household

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#26]
Apart from address, optionally allow setting type of house, size of apartment, family composition (no. of adults / kids), which days of the week you stay home etc.

**Comment by yesgee** [comment]
Update to apartment size and type happens along with update address module 'cos that way it makes more sense.

**Comment by yesgee** [comment]
To do : Update family composition info on adding, removing member? Need to think about this scenario.

**Comment by yesgee** [comment]
Done: Feature to update misc apartment details like size, type, family split.

**Comment by yesgee** [comment]
Closing issue.
