### ISSUE TITLE
Connecting data providers to household

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#27]
After creating the household, we need to provide a way to connect it with a data provider. Note that this may need to support many different data providers, so that should be kept in mind (#28).

**Comment by FruitieX** [comment]
When connecting, there may also be some requirement to show a disclaimer to the user, specific to the data provider, giving us the user's permission to use their data.

**Comment by FruitieX** [comment]
#5 is the first backend we'll need to support

**Comment by yesgee** [comment]
@CodeTaha  TODO: Need to connect usagepoint id to household

**Comment by sanja7s** [comment]
@CodeTaha is this done, or are we waiting to Reply?

**Comment by taha-k** [comment]
Yes I will finish it today.

**Comment by FruitieX** [comment]
Can we close this issue @CodeTaha ?

**Comment by taha-k** [comment]
Right now its connected to endpoints given by Reply. We can create add new paramenters in config.js for other providers, but then api endpoints have to send an additional parameter to connect witha particular data provider. Another issue is that endpoints need to be similar to Reply, else completely new mechanisms will be needed to be applied. However, seems if they are following Greenbutton, then should be almost similar

**Comment by taha-k** [comment]
Household can now be connected to the usagepoint by specifying the usagepoint id and family secret. Anyways there needs some discussion
