### ISSUE TITLE
Allow uploading pictures to comments

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#30]
Things to consider:
- How to store? Just allow uploading an image through a REST API call, then sha256 hash the file and dump the file to disk as <sha256>.<ext>? (+ return path to the user, which they can then include in the comment)
- Size restrictions?
- Can anyone upload?

**Comment by sanja7s** [comment]
is it possible somehow to reduce automatically the image to the size we limit to?

**Comment by FruitieX** [comment]
We agreed on supporting just one image per comment. If the user wants to send more images, they can post more comments.

**Comment by FruitieX** [comment]
Yes, it's possible to reduce the image size, and we should probably do that. For programmers, here's an example library that could be used: https://github.com/aheckmann/gm

A good size limit would be 256x256 pixels. We may want to check using `gm` if either of the image dimensions are over 256 pixels, and in that case scale the image down so it fits the size limit (while keeping aspect ratio...)

**Comment by FruitieX** [comment]
Image is stored on disk with comment's ID. Size restricted (downscaled if needed) to 512x512. Uploading picture happens as a separate REST API call after creating comment.

**Comment by sanja7s** [comment]
Sounds good. 512x512 should be fine size for mobile.
