### ISSUE TITLE
Create relevant indices into the db to speed things up

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#32]
Should be a noticeable speedup once we have lots of data

**Comment by sanja7s** [comment]
true, for Mongo that helps a lot. it is also relatively easy to do, I think.
is it enough to be done once for each collection?

**Comment by FruitieX** [comment]
Yes, for each collection we have to think about according to what data we perform queries, and create indices for those data fields.

**Comment by FruitieX** [comment]
This is best done once we notice some calls being slow (ie. once we have lots of data), it's best to not create unnecessary indices as they will slow things down also!
