### ISSUE TITLE
Implement search for actions and challenges

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#34]
Some stub code is currently there, but it should be implemented so it works.

Have a look at `/api/user/search` for an example how it could be implemented. Let's try to keep searching consistent with how the user search API call works! (change it if needed)

**Comment by FruitieX** [comment]
Copy paste from challenges to actions :)

**Comment by yesgee** [comment]
Right now works for 'search by name' for both challenge and action.

**Comment by FruitieX** [comment]
Perfect, I'll close this issue
