### ISSUE TITLE
Support linking Facebook login to existing account

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#4]
It's currently only possible to either create a local account (email/password) or to create an account via Facebook. But we should also support linking your Facebook profile to an existing account.

**Comment by taha-k** [comment]
ok this can be done, but what if the user has registered fb with another email account and registered with civis with yet another? @FruitieX

**Comment by FruitieX** [comment]
Good point. I think in this case we should use the e-mail that the user registered to civis with. I think it makes sense that we only use the Facebook provided e-mail when a user creates a new account via Facebook.

**Comment by FruitieX** [comment]
Also when registering a new account via Facebook, we should probably check that an account doesn't already exist with the same e-mail as what Facebook provides so we don't get duplicates. Although I think the `passport-local` module already does this!

**Comment by taha-k** [comment]
yea even thats a problem.. Actually what we can do is we can just store the users facebook id in this case.. we should store users fb id even if he is registering through fb. but fb id should be unique.. Then the problem will occur only if 2 people are sharing their fb profile, but then they are stupid.

**Comment by FruitieX** [comment]
Yep we should store the FB id either way. If we get a collision with e-mails it's probably fine to just display an error and tell the user that if they already registered an account with their e-mail and want to link their Facebook account, they should first log in to civis and then from the app settings choose `link with FB account` or similar.

**Comment by taha-k** [comment]
this issue has been closed
