### ISSUE TITLE
Connect household with Apartment Ids

### ISSUE THREAD

**Issue by taha-k** [CIVIS-project/YouPower#45]
For creating or joining a household, user needs to provide apartment ids. Apartment ids privided needs to be checked with Reply if they exist. If household already exist, add the user to the household, else create a new household.

**Comment by FruitieX** [comment]
Similar to #21

**Comment by yesgee** [comment]
This is related to https://github.com/CIVIS-project/YouPower/issues/63. Initially, we give random token for apt id while creating household, post which, when the household is connected to smart meter data, the apt id is fetched from Reply.
