### ISSUE TITLE
Increase test coverage on community ratings code

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#50]
[Here](https://coveralls.io/builds/3074314/source?filename=backend%2Fmodels%2Fusers.js) and [here](https://coveralls.io/builds/3074314/source?filename=backend%2Fmodels%2Fcommunities.js) ;)

**Comment by yesgee** [comment]
Done, except for a few minor coverage misses ;) Latest build [here](https://coveralls.io/builds/3101983).  Might be considered closed. (?)

**Comment by FruitieX** [comment]
Great!
