### ISSUE TITLE
Tags for actions

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#55]
It should be possible to assign tags to actions, such as "daily action", "hardware replacement", "one time action". Further it should be possible to search for actions by these tags. There needs to be an API call that can also autocomplete/suggest actions for when the user is typing in a tag in the frontend (eg. when tagging an action or searching by tags)

**Comment by FruitieX** [comment]
Note: there is a "category" field currently. Tags should replace this.

**Comment by yesgee** [comment]
Tags for actions like daily, repeating etc. Search actions by these tags.
Merged with master -->https://github.com/CIVIS-project/YouPower/pull/64
