### ISSUE TITLE
calculating (accumulated) user action points (number of leafs)

### ISSUE THREAD

**Issue by yilinh** [CIVIS-project/YouPower#57]
user's action points are accumulated each time when a user completed an action. 
The points of an action = (effort + impact)

**Comment by FruitieX** [comment]
Good, we probably want this functionality in the `GET /api/user/profile/*` paths so the frontend can easily display your total leaf count and also the leaf count of others.

As a side note, instead of storing the accumulated value and incrementing it, we can also calculate it each time based on the userAction list. It's a very fast operation even for tens or hundreds of thousands of user actions, and this way we don't need to worry about the points counter ever going out of sync!

**Comment by yilinh** [comment]
think there shall be some way to count user engagement for giving feedbacks of tips + giving comments in chats. how do you think is the best? count these points together with the action points or separate them? In any case, we need a way to count those. I suggest, e.g., a piece of feedback on actions = action points \* 0.3, one comment in discussions = 1 point. i don't know whether this makes sense. anyway, we need to start with something

**Comment by yilinh** [comment]
I am fine with both: weather accumulated or calculate each time. Then the history of users feedback and comments also needs to be save somehow

**Comment by yesgee** [comment]
@yilinh  do you mean discussions as in commenting in actions/top actions in a community? 
We can have discussion thread ( string of comments) in actions in community which we currently don't have.

**Comment by yilinh** [comment]
1) users can comment on actions EnergyUP suggested, right? 
2) users can discuss with each other within a community? 
e.g, each comment can get a point. 
Another issue: can users "like" someone's comments? Each "like" can give the comment's author a point.

**Comment by yilinh** [comment]
@FruitieX  are user points calculated now? is there an API call for this?

**Comment by FruitieX** [comment]
This is now implemented for done user actions as well as given feedback.

**Comment by yilinh** [comment]
Can we do the point like this:
1) completion of an action: x=(effort + impact); let's not *10, the number can become quite big afterwards
2) sending feedback at completion of an action: y=round(x/5), y<1? 1:y
3) give a comment (e.g., about an action in community chat): z=1
4) we may need a flexible way to define how to award points: e.g. completion of 5 actions in a row, be the first participant of an action, completion of user profile.

**Comment by FruitieX** [comment]
- Completion of action now calculated as `effort + impact`
- Sending feedback = 1 leaf
- Posting comment = 1 leaf

**Comment by FruitieX** [comment]
I guess this can be marked as resolved?
