### ISSUE TITLE
User model calls for listing user's communities, actions, challenges

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#6]

**Comment by yesgee** [comment]
For actions, communities and challenges : Get list of names. Any more relevant details?

**Comment by yesgee** [comment]
For list of actions, would it be relevant to show only the list of actions in progress?

**Comment by FruitieX** [comment]
Hmm, maybe we should allow a way of choosing which of the userAction lists are returned (possibly multiple)

**Comment by yesgee** [comment]
Status: The feature is implemented, yet to be tested.

**Comment by yesgee** [comment]
To do: Display 'Completed', 'Current' and 'Pending' actions

**Comment by FruitieX** [comment]
This might need some tweaks after #24, where we change/create a few more "states" for userActions & userCommunities. It might be best to finish that issue before finalizing this one. I'll try to finish it up by the end of today!

**Comment by yesgee** [comment]
So as I see from #24 , actions can now be Pending, In Progress, Done, Declined, Canceled, NA, right?

**Comment by FruitieX** [comment]
That's correct, [here](https://github.com/CIVIS-project/YouPower/blob/e7344adc6c84ed10f04c3610a766f6606aaf388a/backend/models/users.js#L20-L53) are the exact names of the fields inside the user model:

**Comment by yesgee** [comment]
Is it just me or is the 'Declined' category missing in the actions? :)

**Comment by FruitieX** [comment]
Hmm... :P

**Comment by yesgee** [comment]
Implemented for actions and communities. Challenges - Pending. 
For actions, the user can select the type of actions he wants to see.

**Comment by yesgee** [comment]
Regarding challenges, right now there is no reference of challenges in user model to achieve this. May be after https://github.com/CIVIS-project/YouPower/issues/47, we will get a clear idea?

**Comment by FruitieX** [comment]
Yep, just ignore challenges for now. This issue can be closed if it's done for actions and communities.

**Comment by yesgee** [comment]
Implemented for actions and communities.
