### ISSUE TITLE
How to add users to household with or without smart meter data- Pin code invite

### ISSUE THREAD

**Issue by sanja7s** [CIVIS-project/YouPower#63]
Basically, for those users who have smart meter data, we would use usage point id (apartmentId from Reply) -- and what we do for the users who do not have it?

**Comment by yesgee** [comment]
We might also need to think about the flow of control for users with and without smart meter for creating and joining household. Also, how to retain history when user converts to a smart-meter user from non-meter user.

**Comment by yesgee** [comment]
Related to https://github.com/CIVIS-project/YouPower/issues/21

**Comment by sanja7s** [comment]
We distinguish 2 type of users:
1) with SM (smart meter)
2) without SM

and two types of actions:
1) Create a new household
2) Join existing household

**Comment by sanja7s** [comment]
In our household collection in the DB we have 
ApartmentID (to identify households)
FamilyID -- just set for those who have smart meter connection

**Comment by sanja7s** [comment]
For households without SM, we generate the ApartmentID as a long token (only numbers and capital letters) -- and tell to the creator of the household to give this as Apartment ID to other members who want to join.

**Comment by sanja7s** [comment]
For the households with SM (or if a user wants to add SM connection to already existing household), Apartment ID becomes then one from Reply (so in the second case we might need to change it and to notify the user that he now got a new Apartment ID) and then the Family ID is also checked and if correct it becomes set to show that household is now connected to SM.

**Comment by sanja7s** [comment]
As an add on, if frontend ( @yilinh ) can implement QR code for ApartmentID, that might be a nicer way for family members to invite others to join. 
Another options is email invite to family members.

But this is fine without any of those two, if complicated to add.

**Comment by FruitieX** [comment]
Another idea for inviting: Button in the app that shows a one-time 6-digit code that has to be entered on the other device within one minute. It's invalidated after this time or after it's entered correctly. Maybe as additional security, the person who is inviting also has to validate and accept the username of the person who's being invited.

**Comment by danielmiorandi** [comment]
not sure it actually relates to this one, but it might be. For some users we won't have just smart meter data but also data from smart plugs, referring to single appliances. Not sure how they are exposed by Reply backend, but we need to have a way of distinguishing them for visualization purposes.

**Comment by yilinh** [comment]
@danielmiorandi ideally this will be also at Reply backend.

**Comment by yesgee** [comment]
Implemented: Create household, Connect household to smart meter by checking family ID
To do: Generate apartment id token and re-add existing members.

**Comment by yesgee** [comment]
Implemented: Create household, Connect household to smart meter by checking family ID, Add user to existing household with or without smart meter, Generate Apartment ID token for household without smart meter

**Comment by yesgee** [comment]
This is done and tested now. As for the apartment ID random token (for those without smart meter), right now we generate a 16byte pseudo random token. The security level of this can be discussed in meeting

**Comment by FruitieX** [comment]
I can do the PIN code part, if it's ok assign the issue to me?

**Comment by yesgee** [comment]
Done!

**Comment by FruitieX** [comment]
We agreed to handle this via owner inviting by username instead of PIN codes.
