### ISSUE TITLE
Production endpoint

### ISSUE THREAD

**Issue by danielmiorandi** [CIVIS-project/YouPower#68]
We need a /api/production endpoint. Similar behaviour and parameters as the /consumption one, but just for usage with production data

**Comment by taha-k** [comment]
API production endpoint is already there in consumption. Its just that you have to set the c_type parameter to S_CONS. Anyways if you need a new API endpoint I will create one

**Comment by danielmiorandi** [comment]
got it, pls update API documentation accordingly so that we can be aligned ;)

**Comment by taha-k** [comment]
Document is updated. U just have to change the ctype to S_PROD for production and S_CONS for consumption in /api/consumption/downloadMyData
