### ISSUE TITLE
endpoint for list of appliances monitored

### ISSUE THREAD

**Issue by danielmiorandi** [CIVIS-project/YouPower#72]
need an endpoint (e.g., /api/consumption/appliance) from which to retrieve a list of appliances monitored for a given user. Parameters shall include userID and token. The response shall include a list of appliances ID together with some descriptive field (e.g., 'dishwater').

**Comment by taha-k** [comment]
@danielmiorandi Yes I would do that. Anyways, just to remove the obfuscation of using different names at different place, we use 'sensors' instead of 'appliance'.

**Comment by taha-k** [comment]
@FruitieX @danielmiorandi  Ok we have an issue here. There is somethn called as appliance, which user adds. also from Reply, we have sensors connected to a household through UsagePoints. Sensors basically have an appliance name like 'refrigerator'. There is a mix of terms here.. we have appliance as well as sensors.. Should it be that we fetch both and return?

**Comment by danielmiorandi** [comment]
from the app perspective I'd keep appliance as name of the endpoint (from a semantic perspective that's what the app cares about), then you have full freedom on how the backend translates this in a suitable call to the Reply platform. I just need the endpoint and an indication of the format of the response ;)

**Comment by taha-k** [comment]
ok so there are 2 cases here. If the user does not have energy data, then appliances are only shown which he has added in his household. If user has energy data, then sensors are shown as well along with the appliances if added any. the final output will be this 
[
    {
        "appliances": [
            {
                "appliance": "Washing Machine",
                "quantity": 2,
                "_id": "55d2f971dfe4845d50451705"
            },
            {
                "appliance": "Heater",
                "quantity": 4,
                "_id": "55d2f971dfe4845d50451704"
            }
        ]
    },
    {
        "sensors": [
            {
                "_id": "55d2ef2f739304394f9f079f",
                "sensorNumber": 0,
                "sensorType": 0,
                "measureUnit": "Wh",
                "label": "Consumo Elettrico",
                "lastSampleTimestamp": "2015-07-10T15:42:11.000Z",
                "_apartmentId": "55d2ef2f739304394f9f0795",
                "__v": 0
            },
            {
                "_id": "55d2ef2f739304394f9f07a0",
                "sensorNumber": 1,
                "sensorType": 1,
                "measureUnit": "Wh",
                "label": "Freezer",
                "lastSampleTimestamp": "2015-07-10T15:45:23.000Z",
                "_apartmentId": "55d2ef2f739304394f9f0795",
                "__v": 0
            },
            {
                "_id": "55d2ef2f739304394f9f07a1",
                "sensorNumber": 2,
                "sensorType": 1,
                "measureUnit": "Wh",
                "label": "Lavatrice",
                "lastSampleTimestamp": "2015-07-10T15:38:31.000Z",
                "_apartmentId": "55d2ef2f739304394f9f0795",
                "__v": 0
            },
            {
                "_id": "55d2ef2f739304394f9f07a2",
                "sensorNumber": 32,
                "sensorType": 32,
                "measureUnit": "°C",
                "label": "Temp. Interna",
                "lastSampleTimestamp": "2015-07-10T15:45:14.000Z",
                "_apartmentId": "55d2ef2f739304394f9f0795",
                "__v": 0
            }
        ]
    }
]
