### ISSUE TITLE
Allow choosing according to what field search results are sorted

### ISSUE THREAD

**Issue by FruitieX** [CIVIS-project/YouPower#8]
Could apply to all sorts of API & DB calls that return lists of some kind

**Comment by FruitieX** [comment]
To clarify: it should be possible through the REST API calls to supply a sorting order, especially where entries are paginated so that we can get every result in the desired order. Mongoose has .sort() for this, we just need to come up with a way to pass the parameter we want to it.

**Comment by sanja7s** [comment]
for now we have search by the name only.
if needed more fields, then this becomes relevant.
